#!/usr/bin/env php
<?php
/**
 * Main script
 *
 * 1. Make copy of this file:
 * cp refactorer-example refactorer
 *
 * 2. Modify local settings
 *
 * 3. Run script using command:
 * ./refactorer <path to files>
 *
 * @file    refactorer-example
 *
 * PHP version 5.4+
 *
 * @author  Yancharuk Alexander <alex@itvault.info>
 * @date    Tue Mar 4 15:46:40 2014
 * @copyright The BSD 3-Clause License.
 */

use Classes\PathExclusions;
use Classes\RegexRule;
use Classes\RulesHandler;
use Veles\AutoLoader;
use Application\RefApplication;
use Classes\FileContentReader;

define('BASE_PATH', realpath(__DIR__));

setlocale(LC_ALL, 'ru_RU.utf8');
date_default_timezone_set('Europe/Moscow');

require 'lib/Veles/AutoLoader.php';
AutoLoader::registerPath(BASE_PATH . '/lib');
AutoLoader::init();

if ($argc < 1) {
	$error = <<<EOT
	refactorer: missing parameters

	USAGE: ./refactorer <path to files>

EOT;

	die($error);
}

$pattern = <<<EOF
Place here your pattern
EOF;
$replacement = <<<EOF
Place here your replacement text
EOF;

$rule = new RegexRule;
$rule->setPattern($pattern)
	->setReplacement($replacement);

$exclusions = new PathExclusions;
$exclusions->setPaths(['excluded.file', 'another-excluded.file']);
$exclusions->setAbsolutePaths([
	'/example/of/excluded.file',
	'/path/to/another-excluded.file'
]);
$reader  = new FileContentReader($argv[1], ['php'], $exclusions);
$handler = new RulesHandler;
$handler->addRule($rule);

$app = new RefApplication;
$app->setReader($reader)
	->setRulesHandler($handler)
	->run();
